# Generated by Django 3.2.7 on 2021-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Супервайзер', 'Супервайзер'), ('Врач координатор', 'Врач координатор'), ('Заказчик', 'Заказчик'), ('Администратор', 'Администратор')], max_length=200, null=True),
        ),
    ]
