# Generated by Django 3.2.7 on 2021-09-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num1', models.IntegerField()),
                ('service1', models.CharField(max_length=500)),
                ('description1', models.TextField(max_length=500)),
                ('categories1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num2', models.IntegerField()),
                ('service2', models.CharField(max_length=500)),
                ('description2', models.TextField(max_length=500)),
                ('categories2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num3', models.IntegerField()),
                ('service3', models.CharField(max_length=500)),
                ('description3', models.TextField(max_length=500)),
                ('categories3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num4', models.IntegerField()),
                ('service4', models.CharField(max_length=500)),
                ('description4', models.TextField(max_length=500)),
                ('categories4', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num5', models.IntegerField()),
                ('service5', models.CharField(max_length=500)),
                ('description5', models.TextField(max_length=500)),
                ('categories5', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num6', models.IntegerField()),
                ('service6', models.CharField(max_length=500)),
                ('description6', models.TextField(max_length=500)),
                ('categories6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num7', models.IntegerField()),
                ('service7', models.CharField(max_length=500)),
                ('description7', models.TextField(max_length=500)),
                ('categories7', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num8', models.IntegerField()),
                ('service8', models.CharField(max_length=500)),
                ('description8', models.TextField(max_length=500)),
                ('categories8', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num9', models.IntegerField()),
                ('service9', models.CharField(max_length=500)),
                ('description9', models.TextField(max_length=500)),
                ('categories9', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
                ('num10', models.IntegerField()),
                ('service10', models.CharField(max_length=500)),
                ('description10', models.TextField(max_length=500)),
                ('categories10', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20)),
            ],
        ),
    ]
