# Generated by Django 3.2.7 on 2021-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description1',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description10',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description3',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description4',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description5',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description6',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description7',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description8',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description9',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service10',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service6',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service7',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service8',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service9',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
