# Generated by Django 3.2.7 on 2021-09-15 21:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteragent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birthday', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('police_num', models.CharField(max_length=20)),
                ('date_start_police', models.DateField()),
                ('date_finish_police', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=datetime.datetime(2021, 9, 15, 21, 51, 8, 674463, tzinfo=utc))),
                ('info', models.TextField(max_length=5000)),
                ('task', models.CharField(choices=[('скорая помощь', 'скорая помощь'), ('амбулаторная помощь', 'амбулаторная помощь'), ('стоматология', 'стоматология'), ('прогарантировать', 'прогарантировать')], max_length=20)),
                ('diagnoz', models.TextField(max_length=1500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteragent.lpu')),
            ],
        ),
        migrations.CreateModel(
            name='MKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mkb', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_case', models.IntegerField()),
                ('date_start_appeal', models.DateTimeField(default=datetime.datetime(2021, 9, 15, 21, 51, 8, 673463, tzinfo=utc))),
                ('date_finish_appeal', models.DurationField()),
                ('status', models.BooleanField()),
                ('coordinator', models.CharField(max_length=2000)),
                ('diagnoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientappeal')),
                ('mkb_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mkb')),
            ],
        ),
    ]
