# Generated by Django 3.2.7 on 2021-09-18 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contractbase', '0001_initial'),
        ('account', '0002_alter_employee_position'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_case', models.IntegerField(null=True)),
                ('case_start_date', models.DateField(default=datetime.datetime(2021, 9, 18, 17, 38, 37, 762229, tzinfo=utc), null=True)),
                ('case_end_date', models.DateField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientcase',
            name='diagnoz',
        ),
        migrations.RemoveField(
            model_name='clientcase',
            name='mkb_block',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_finish_police',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_start_police',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='police_num',
        ),
        migrations.RemoveField(
            model_name='client',
            name='program',
        ),
        migrations.AddField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='policy_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='policy_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='policy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractbase.contract'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ClientAppeal',
        ),
        migrations.DeleteModel(
            name='ClientCase',
        ),
        migrations.DeleteModel(
            name='MKB',
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='case',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee'),
        ),
    ]
