# Generated by Django 3.2.7 on 2021-09-18 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210918_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_start_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 17, 49, 57, 480932, tzinfo=utc), null=True),
        ),
    ]
