# Generated by Django 3.2.7 on 2021-09-21 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_case_case_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_start_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 21, 44, 52, 317287, tzinfo=utc), null=True),
        ),
    ]
